# Generated by Django 3.1.7 on 2021-04-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WgUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(unique=True)),
                ('public_key', models.CharField(max_length=44)),
                ('expire_date', models.DateField()),
                ('alias', models.CharField(max_length=50)),
            ],
        ),
    ]
