# Generated by Django 3.1.7 on 2021-04-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgusers', '0002_auto_20210411_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='wguser',
            name='private_key',
            field=models.CharField(default='your private key', max_length=44),
        ),
    ]
